language: node_js
node_js:
  - 'node'
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE palette_picker_test;' -U postgres
  - -c 'knex migrate:latest --env test'
  - -c 'knex seed:run --env=test'

notifications:
  email: false
